services:
  php:
    build:
      target: deploy
      dockerfile: Dockerfile.php
    networks:
      - web-public
    volumes:
      - "database:/var/www/html/.infrastructure/volume_data/sqlite/"
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    environment:
      AUTORUN_ENABLED: "true" # 👈 Remove this line if you don't want Laravel Automations
      PHP_OPCACHE_ENABLE: "1"
      SSL_MODE: "full"

volumes:
  database:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:

networks:
  web-public:
